language: julia
os:
    - linux
    - osx
julia:
    - 0.5
    - nightly
env:
  global:
    - PYTHON=conda

before_install:
    #install mpmath to test functionallity
  - julia -e 'ENV["PYTHON"]=""; Pkg.add("PyCall"); Pkg.build("PyCall")'
  - julia -e 'Pkg.add("Conda"); using Conda; Conda.add("SymPy")'
