# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
      - linux
      - osx
julia:
      - release
      - nightly
env:
      global:
      - PYCALL_DEBUG_BUILD="yes"
      matrix:
      - PYTHON=python  # python 2.7
      - PYTHON=python3 # python 3.5
      - PYTHON=Conda-python # not actually a python version, here to test Conda.jl's python

notifications:
      email: kelvyn.baruc@gmail.com
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("OptimJulia"); Pkg.test("OptimJulia"; coverage=true)'
