language: julia
os:
    - linux
    - osx
julia:
    - 0.5
    - nightly
env:
  global:
    - PYTHON=conda
  global:

before_install:
    #install mpmath to test functionallity
  - julia -e 'Pkg.add("Conda"); using Conda; Conda.add("SymPy")'
